version: '3.5'
services:
  wikijv:
    build: ./WikiJV
    command: "ng serve --host 0.0.0.0 --port 4200"
    ports: 
      - 42000:4200
  projet-angular-cours-apinest-js:
    build: ./projet-angular-cours-apinest-js
    command: "npm run start"
    ports: 
      - 3000:3000